spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    password: Cisco12341234
    url: spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCPS)(HOST=adb.mx-queretaro-1.oraclecloud.com)(PORT=1522))(CONNECT_DATA=(SERVICE_NAME=g269731c703fe63_reacttodovm8eb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: TODOUSER
  jpa:
    database: ORACLE
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: Team24
      password: Cisco12341234
  Oracle:
  Wallet-location: oci-react-samples\MtdrSpring\Wallet_reacttodovm8eb

#spring:
#  datasource:
#    driver_class_name: oracle.jdbc.OracleDriver
#    password: PeterSong123
#    url: jdbc:oracle:thin:@petertestdb_medium?TNS_ADMIN=/Users/psong/Downloads/Wallet_petertestDB
#    username: TODOUSER
#  jpa:
#    database: ORACLE
#    database-platform: org.hibernate.dialect.Oracle12cDialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  security:
#    user:
#      name: ${ui_username}
#      password: ${ui_password}